ER_MAP = {
    "1000": {"er_name": "Newfoundland and Labrador", "province": "NL"},
    "1010": {"er_name": "Avalon Peninsula", "province": "NL"},
    "1020": {"er_name": "South Coast - Burin Peninsula", "province": "NL"},
    "1030": {"er_name": "West Coast - Northern Peninsula - Labrador", "province": "NL"},
    "1040": {"er_name": "Notre Dame - Central Bonavista Bay", "province": "NL"},
    "1110": {"er_name": "Prince Edward Island", "province": "PE"},
    "1200": {"er_name": "Nova Scotia", "province": "NS"},
    "1210": {"er_name": "Cape Breton", "province": "NS"},
    "1220": {"er_name": "North Shore", "province": "NS"},
    "1230": {"er_name": "Annapolis Valley", "province": "NS"},
    "1240": {"er_name": "Southern", "province": "NS"},
    "1250": {"er_name": "Halifax", "province": "NS"},
    "1300": {"er_name": "New Brunswick", "province": "NB"},
    "1310": {"er_name": "Campbellton - Miramichi", "province": "NB"},
    "1320": {"er_name": "Moncton - Richibucto", "province": "NB"},
    "1330": {"er_name": "Saint John - St. Stephen", "province": "NB"},
    "1340": {"er_name": "Fredericton - Oromocto", "province": "NB"},
    "1350": {"er_name": "Edmundston - Woodstock", "province": "NB"},
    "2400": {"er_name": "Quebec", "province": "QC"},
    "2410": {"er_name": "Gaspésie - Îles-de-la-Madeleine", "province": "QC"},
    "2415": {"er_name": "Bas-Saint-Laurent", "province": "QC"},
    "2420": {"er_name": "Capitale-Nationale", "province": "QC"},
    "2425": {"er_name": "Chaudière - Appalaches", "province": "QC"},
    "2430": {"er_name": "Estrie", "province": "QC"},
    "2433": {"er_name": "Centre-du-Québec", "province": "QC"},
    "2435": {"er_name": "Montérégie", "province": "QC"},
    "2440": {"er_name": "Montréal", "province": "QC"},
    "2445": {"er_name": "Laval", "province": "QC"},
    "2450": {"er_name": "Lanaudière", "province": "QC"},
    "2455": {"er_name": "Laurentides", "province": "QC"},
    "2460": {"er_name": "Outaouais", "province": "QC"},
    "2465": {"er_name": "Abitibi - Témiscamingue", "province": "QC"},
    "2470": {"er_name": "Mauricie", "province": "QC"},
    "2475": {"er_name": "Saguenay - Lac-Saint-Jean", "province": "QC"},
    "2480": {"er_name": "Côte-Nord", "province": "QC"},
    "2490": {"er_name": "Nord-du-Québec", "province": "QC"},
    "3500": {"er_name": "Ontario", "province": "ON"},
    "3510": {"er_name": "Ottawa", "province": "ON"},
    "3515": {"er_name": "Kingston - Pembroke", "province": "ON"},
    "3520": {"er_name": "Muskoka - Kawarthas", "province": "ON"},
    "3530": {"er_name": "Toronto", "province": "ON"},
    "3540": {"er_name": "Kitchener - Waterloo - Barrie", "province": "ON"},
    "3550": {"er_name": "Hamilton - Niagara Peninsula", "province": "ON"},
    "3560": {"er_name": "London", "province": "ON"},
    "3570": {"er_name": "Windsor - Sarnia", "province": "ON"},
    "3580": {"er_name": "Stratford - Bruce Peninsula", "province": "ON"},
    "3590": {"er_name": "Northeast", "province": "ON"},
    "3595": {"er_name": "Northwest", "province": "ON"},
    "4600": {"er_name": "Manitoba", "province": "MB"},
    "4610": {"er_name": "Southeast", "province": "MB"},
    "4620": {"er_name": "South Central", "province": "MB"},
    "4630": {"er_name": "Southwest", "province": "MB"},
    "4640": {"er_name": "North Central", "province": "MB"},
    "4650": {"er_name": "Winnipeg", "province": "MB"},
    "4660": {"er_name": "Interlake", "province": "MB"},
    "4670": {"er_name": "Parklands", "province": "MB"},
    "4680": {"er_name": "North", "province": "MB"},
    "4700": {"er_name": "Saskatchewan", "province": "SK"},
    "4710": {"er_name": "Regina - Moose Mountain", "province": "SK"},
    "4720": {"er_name": "Swift Current - Moose Jaw", "province": "SK"},
    "4730": {"er_name": "Saskatoon - Biggar", "province": "SK"},
    "4740": {"er_name": "Yorkton - Melville", "province": "SK"},
    "4750": {"er_name": "Prince Albert", "province": "SK"},
    "4760": {"er_name": "Northern", "province": "SK"},
    "4800": {"er_name": "Alberta", "province": "AB"},
    "4810": {"er_name": "Lethbridge - Medicine Hat", "province": "AB"},
    "4820": {"er_name": "Camrose - Drumheller", "province": "AB"},
    "4830": {"er_name": "Calgary", "province": "AB"},
    "4840": {"er_name": "Banff - Jasper - Rocky Mountain House", "province": "AB"},
    "4850": {"er_name": "Red Deer", "province": "AB"},
    "4860": {"er_name": "Edmonton", "province": "AB"},
    "4870": {"er_name": "Athabasca - Grande Prairie - Peace River", "province": "AB"},
    "4880": {"er_name": "Wood Buffalo - Cold Lake", "province": "AB"},
    "5900": {"er_name": "British Columbia", "province": "BC"},
    "5910": {"er_name": "Vancouver Island and Coast", "province": "BC"},
    "5920": {"er_name": "Lower Mainland - Southwest", "province": "BC"},
    "5930": {"er_name": "Thompson - Okanagan", "province": "BC"},
    "5940": {"er_name": "Kootenay", "province": "BC"},
    "5950": {"er_name": "Cariboo", "province": "BC"},
    "5960": {"er_name": "North Coast", "province": "BC"},
    "5970": {"er_name": "Nechako", "province": "BC"},
    "5980": {"er_name": "Northeast", "province": "BC"},
    "6010": {"er_name": "Yukon", "province": "YK"},
    "6110": {"er_name": "Northwest Territories", "province": "NT"},
    "6210": {"er_name": "Nunavut", "province": "NU"},
}
